# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff2d9a3c3b70998eb3da50a14cea4c3ade0917029ca0aa22eca9e3be2c1339defec124356c0688e7ebd03fdc671bac7a0a6827a00fed049370701e07e758b5d

test:
  secret_key_base: e36528a45ff26ad05a6e325959b8769675ce255e46878975e9f572dc3d83071b7b2f76b464f7ce5c6827acec51c68cd72a7ea37dc2cf00cc787e7fdc84c88db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
